apiVersion: skaffold/v2beta10
kind: Config

metadata:
  name: edsc-microk8s-controller

build:
  artifacts:
    - image: farberg/edsc-microk8s-controller
      context: .
      docker:
        dockerfile: Dockerfile
      #kaniko:
      #  dockerfile: Dockerfile
      #  noPush: true
      #  verbosity: debug
  #cluster: {}

deploy:
  kubectl:
    manifests:
      - config/k8s-deployment.yaml

profiles:
  - name: Development Profile
    activation:
      - command: dev
    patches:
      - op: replace
        path: /build/artifacts/0/docker/dockerfile
        #path: /build/artifacts/0/kaniko/dockerfile
        value: Dockerfile.dev
      - op: replace
        path: /deploy/kubectl/manifests/0
        value: config/k8s-deployment-dev.yaml

  - name: Run Profile
    activation:
      - command: run
    patches:
      - op: replace
        path: /build/artifacts/0/docker/dockerfile
        #path: /build/artifacts/0/kaniko/dockerfile
        value: Dockerfile.dev
      - op: replace
        path: /deploy/kubectl/manifests/0
        value: config/k8s-deployment-dev.yaml
