apiVersion: apps/v1
kind: Deployment
metadata:
  name: edsc-microk8s-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "edsc-microk8s-controller"
  template:
    metadata:
      labels:
        app: "edsc-microk8s-controller"
    spec:
      containers:
        - name: controller
          image: farberg/edsc-microk8s-controller
          ports:
            - containerPort: 8080
          args:
            - "--mode"
            - "development"
            - "--verbose"
            - "--hostname"
            - "edsc-microk8s-controller-service"
            - "--dump-open-files"
            - "/debug-volume/open-files.txt"
          volumeMounts:
            - mountPath: /debug-volume
              name: debug-volume
      volumes:
        - name: debug-volume
          hostPath:
            # directory location on host
            path: /opt/debug-volume
            # this field is optional
            type: Directory

---
apiVersion: v1
kind: Service
metadata:
  name: edsc-microk8s-controller-service
spec:
  selector:
    app: "edsc-microk8s-controller"
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
